version: "3"
services:
  # for building the app
  sbt-service:
    build: ./build/docker/sbt-service/
    working_dir: /app
    volumes:
      # application source
      - .:/app
      # build cache
      - $HOME/.ivy2:/root/.ivy2
      - $HOME/.sbt:/root/.sbt
      - $HOME/.m2:/root/.m2

  # app docker image
  app:
    build: ./target/docker/
    working_dir: /app
