steps:
  - name: "just ls"
    label: ":construction_worker:"
    command: "ls"
    plugins:
      docker-compose#v2.1.0:
        run: sbt-service
  - name: "cat build.sbt"
    label: ":construction_worker:"
    command: "cat build.sbt"
    plugins:
      docker-compose#v2.1.0:
        run: sbt-service
  - name: "cat project/build.properties"
    label: ":construction_worker:"
    command: "cat project/build.properties"
    plugins:
      docker-compose#v2.1.0:
        run: sbt-service
  - name: "docker image stage"
    label: ":construction_worker:"
    command: "sbt docker:publishLocal"
    plugins:
      docker-compose#v2.1.0:
        run: sbt-service
