steps:
  - label: ":sbt: :docker: stage"
    command: "sbt docker:stage"
    artifact_paths:
      - "target/docker/**/*"
    plugins:
      docker-compose#v2.5.1:
        run: sbt-service
        config: build/docker/docker-compose.yml

  - wait

  - label: ":docker: build"
    command:
      # download artifact created by the `docker-stage` step
      - "buildkite-agent artifact download target/docker/* ."
      # build docker image
      - "BUILDKITE_SHORT_COMMIT=$(git rev-parse --short $BUILDKITE_COMMIT); docker build -t buildkite-trial:${BUILDKITE_BRANCH}.${BUILDKITE_SHORT_COMMIT} target/docker/stage/"