steps:
  - label: ":man-facepalming:"
    command: "find /app"
    plugins:
      docker-compose#v2.5.1:
        run: sbt-service
  - label: ":sbt:"
    command: "sbt docker:stage"
    plugins:
      docker-compose#v2.5.1:
        run: sbt-service
